### ISSUE TITLE
Failed running npm install

### ISSUE THREAD

**Issue by remo87** [mateuszsokola/2048-in-react#2]
Hi @mateuszsokola I tried cloning the code and running npm install and I got this error: 

`npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path C:\Code\react\2048-in-react\node_modules\eslint\package.json.1677480921
npm ERR! dest C:\Code\react\2048-in-react\node_modules\eslint\package.json
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Code\react\2048-in-react\node_modules\eslint\package.json.1677480921' -> 'C:\Code\react\2048-in-react\node_modules\eslint\package.json'
npm ERR!  [OperationalError: EPERM: operation not permitted, rename 'C:\Code\react\2048-in-react\node_modules\eslint\package.json.1677480921' -> 'C:\Code\react\2048-in-react\node_modules\eslint\package.json'] {      
npm ERR!   cause: [Error: EPERM: operation not permitted, rename 'C:\Code\react\2048-in-react\node_modules\eslint\package.json.1677480921' -> 'C:\Code\react\2048-in-react\node_modules\eslint\package.json'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'rename',
npm ERR!     path: 'C:\\Code\\react\\2048-in-react\\node_modules\\eslint\\package.json.1677480921',
npm ERR!     dest: 'C:\\Code\\react\\2048-in-react\\node_modules\\eslint\\package.json'
npm ERR!   },`

**Comment by mateuszsokola** [comment]
Hi @remo87, 

Sorry for the late reply. Just noticed your message.

It seems like it is a permission problem on your machine. I'm not a Windows user but it seems like you Windows Subsystem for Linux (WSL) cannot write to your home directory.
